[package]
name = "narrowlink-types"
version = "0.0.2"
edition = "2021"
description = "Narrowlink Types Library"
readme = "README.md"
homepage = "https://narrowlink.com"
repository = "https://github.com/narrowlink/narrowlink/"
license = 'MPL-2.0'
keywords = ["narrowlink"]
authors = ['Narrowlink <opensource@narrowlink.com>']

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
]

[dependencies]
uuid = { version = "*", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "*"
jsonwebtoken = { version = "*" }
ipnet = { version = "*", features = ["serde"] }
wildmatch = { version = "*" }
validator = { version = "*", features = ["derive"] }
regex = "*"
hmac = { version = "*", default-features = false }
sha3 = { version = "*", default-features = false }
chrono = { version = "*", default-features = false,features = ["clock"] }
